--
-- PostgreSQL database dump
--

-- Dumped from database version 9.1.5
-- Dumped by pg_dump version 9.1.5
-- Started on 2013-03-14 15:53:17

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = source, pg_catalog;

--
-- TOC entry 3379 (class 0 OID 23610)
-- Dependencies: 206 3380
-- Data for Name: administrative_source_type; Type: TABLE DATA; Schema: source; Owner: postgres
--Insert Document types for Lesotho data
DELETE FROM source.administrative_source_type;

INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('deed', 'Deed', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('agreement', 'Agreement', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('agriConsent', 'Agricultural Consent', 'x', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('agriLease', 'Agricultural Lease', 'x', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('agriNotaryStatement', 'Agricultural Notary', 'x', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('cadastralMap', 'Cadastral Map::::Mapa oa Cadastral', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('cadastralSurvey', 'Plan of Survey (S10)::::Cadastral Survey', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('declareLandHold', 'Declaration of Land Holdings', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('legalNotice', 'Legal Notice', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('contractForSale', 'Contract For Sale::::Tumellano ea Thekisetsano', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('mortgage', 'Mortgage Bond::::Mortgage', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('powerOfAttorney', 'Power of Attorney', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('proclamation', 'Proclamation', 'x', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('otherDocument', 'Other Documents', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('groundRentExemp', 'Ground Rent Exemption Application', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('title', 'Allocation Title::::Lengolo le pakang', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('waiver', 'Waiver', 'x', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('will', 'Last Will and Testament::::Thato ea Mofu', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('cessionDeed', 'Cession of Deed', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('cessionLease', 'Cession of Lease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('letterCouncil', 'Letter from Council', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('memoArticles', 'Memorandum of Articles', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('mineLease', 'Mining Lease::::Lisi ea Mine', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('sublease', 'Sub-Lease Contract::::Sublease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('surrLease', 'Surrender of Lease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('surveyReport', 'Survey Report', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('titleDeed', 'Title Deed', 'c', NULL, true);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('lease', 'Lease::::Lisi', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('notarialSuretyBond', 'Notarial Surety Bond', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('notarialCoveringBond', 'Notarial Covering Bond', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('notarialDeedServitud', 'Notarial Deed of Servitude', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('notarialGeneralBond', 'Notarial General Bond', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('reducblMortgageBond', 'Reducible Mortgage Bond', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('specialNotarialBond', 'Special Notarial Bond', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('addendumSublease', 'Addendum to Sublease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('certofIcoporation', 'Certificate of Incorporation', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('courtOrder', 'Court Order::::Taelo ea Lekhotla', 'c', 'Extension to LADM', false);
INSERT INTO administrative_source_type VALUES ('idVerification', 'Identification Document::::Boitsebiso', 'c', 'Extension to LADM', false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('marriageCert', 'Marriage Certificate::::Lengolo la Lenyalo', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('landUseCert', 'Land Use Certificate', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('valuationRep', 'Valuation Report', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('offPaymentRecpt', 'Official Payment Receipt', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('swornAffdt', 'Sworn Affidavit', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('propertyMarktRep', 'Property Market Value Report', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('changeUseApp', 'Change of Use Approval', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('consentCert', 'Consent Certificate', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('deathCert', 'Death Certificate', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('ministerialCons', 'Ministerial Consent', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('leaseCopy', 'Copy of lease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('subDivideLease', 'Subdivide a Lease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('surveyPlan', 'Plan of Survey', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('leaseTransfer', 'Transfer of Lease', 'c', NULL, false);
INSERT INTO source.administrative_source_type(code,display_value,status,description,is_for_registration) VALUES ('appForm', 'Application Form', 'c', NULL, false);

--Insert request types for Lesotho data
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.1.5
-- Dumped by pg_dump version 9.1.5
-- Started on 2013-03-19 08:49:34

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = application, pg_catalog;

--
-- TOC entry 3390 (class 0 OID 23860)
-- Dependencies: 226 3391
-- Data for Name: request_type; Type: TABLE DATA; Schema: application; Owner: postgres

DELETE FROM application.request_type;

--A Section with status 'c'
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regnReducMortgage', 'registrationServices', 'Register Reducible Mortgage', NULL, 'c', 5, 5.00, 1.00, 0.00, 1, NULL, NULL, 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cancServitude', 'registrationServices', 'Cancel Servitude', NULL, 'c', 5, 5.00, 1.00, 0.00, 1, NULL, NULL, 'cancel');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regnDeeds', 'registrationServices', 'Register Notarial Bond', NULL, 'c', 3, 1.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cnclPowerOfAttorney', 'registrationServices', 'Cancel Power of Attorney', NULL, 'c', 1, 5.00, 0.00, 0.00, 0, NULL, NULL, 'cancel');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cnclDocument', 'registrationServices', 'Withdraw Document', 'To withdraw from use any standard document (such as standard mortgage or standard lease)', 'c', 1, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('provideSpatialData', 'informationServices', 'Provide Spatial Data::::Fana ka  boitsebiso ba spatial Data', 'Provide Spatial Data', 'c', 1, 0.00, 0.00, 0.00, 1, 'Provide Spatial Data', NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cadastreChange', 'cadastreServices', 'Change to Cadastre::::Phetoho ho Cadaster', NULL, 'c', 30, 25.00, 0.10, 0.00, 1, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('caveat', 'registrationServices', 'Register Caveat', NULL, 'c', 5, 50.00, 0.00, 0.00, 1, 'Caveat in the name of <name>', 'caveat', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('documentSearch', 'informationServices', 'Document Search', NULL, 'c', 1, 5.00, 0.00, 0.00, 1, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('servitude', 'registrationServices', 'Register Servitude', NULL, 'c', 5, 5.00, 0.00, 0.00, 1, 'Servitude over <parcel1> in favour of <parcel2>', 'servitude', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cancelMortBonds', 'registrationServices', 'Cancellation of Mortgage Bonds', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('consentApp', 'registrationServices', 'Consent Application', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regRedMortBond', 'registrationServices', 'Register Reducable Mortgage Bond', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('varyMortgage', 'registrationServices', 'Vary Mortgage Application::::kopo eaFetola Mortgage', NULL, 'x', 1, 5.00, 0.00, 0.00, 1, 'Change on the mortgage', 'mortgage', 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('counterClaim', 'legalServices', 'Lodge Counter Claim', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('courtProcess', 'legalServices', 'Lodge Court Process', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('disputeReg', 'legalServices', 'Lodge Regularization Dispute', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('disputeSpdic', 'legalServices', 'Lodge Sporadic Dispute', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('lodgeObjection', 'legalServices', 'Lodge Objection', NULL, 'c', 90, 5.00, 0.00, 0.00, 1, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('exempApp', 'registrationServices', 'Ground Rent Exemption Application', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('documentCopy', 'informationServices', 'Document Copy::::Kopi ea tokomane', NULL, 'c', 1, 0.50, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('copyLostDeed', 'registrationServices', 'Copy of Lost Deed::::kopi ea deed', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
insert into application.request_type(code, request_category_code, display_value, status, nr_days_to_complete, base_fee, area_base_fee, value_base_fee, nr_properties_required, notation_template, rrr_type_code, type_action_code) values('varyLease', 'registrationServices', 'Register Variation of Lease::::Modifica affitto', 'c', 5, 5.00, 0.00, 0, 1, 'Variation of Lease <reference>', 'lease', 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('serviceEnquiry', 'informationServices', 'Service Enquiry::::Kopo ea Tshebeletso', NULL, 'c', 1, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('mortgage', 'registrationServices', 'Register Mortgage Bond::::Ngolisa Mortgage', NULL, 'c', 5, 5.00, 0.00, 0.00, 1, 'Mortgage to <lender>', 'mortgage', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regSpecNotBond', 'registrationServices', 'Register Special Notarial Bond', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regNotcovBond', 'registrationServices', 'Register Notarial Covering Bond', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regNotarSuretyBond', 'registrationServices', 'Register Notarial Surety Bond', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regCessionDeed', 'registrationServices', 'Register Cession of Deed', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('mapSale', 'informationServices', 'Map Sales', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('jointUseLand', 'registrationServices', 'Joint Use of Land Application', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('groundRentCalc', 'informationServices', 'Ground Rent Calculation', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('printSurveyApp', 'informationServices', 'Print Survey Approval (S10)::::Hatisa S10', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('printSurveyDiag', 'informationServices', 'Print Survey Diagram::::Ngolisa Mapa oa Mapotiele', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);

INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regNotGenBond', 'registrationServices', 'Register Notarial General Bond', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('RegMiningLease', 'registrationServices', 'Register Mining Lease::::Ngolisa Lease ea Mine', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regNotDeedSer', 'registrationServices', 'Register Notarial Deed of Servitude', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regSublease', 'registrationServices', 'Register Sublease::::Ngolisa sublease', NULL, 'c', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('examSurveyFiles', 'cadastreServices', 'Examination of Survey Files::::Thlahlobo ea File', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('foreignEntHoldTitle', 'registrationServices', 'Foreign Enterprise to Hold Title to Land', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regSurrenderLease', 'registrationServices', 'Register Surrender of a Lease', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('printAllocMap', 'informationServices', 'Print Allocation Maps::::Hatisa Mapa', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('newOwnership', 'registrationServices', 'Register Deed of Transfer::::Ngolisa Phetisetso', NULL, 'c', 5, 5.00, 0.00, 0.02, 1, 'Transfer to <name>', 'ownership', 'vary');
insert into application.request_type(code,request_category_code,display_value,status, nr_days_to_complete, base_fee, area_base_fee, value_base_fee, nr_properties_required, notation_template, rrr_type_code, type_action_code) values('registerLease', 'registrationServices', 'Register Lease::::Registrazione affitto', 'c', 5, 5.00, 0.00, 0.01, 1, 'Lease of nn years to <name>', 'lease', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('printMap', 'informationServices', 'Print Map::::Hatisa Mapa', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('leaseTrans', 'legalServices', 'Register Lease Transmission', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('leaseSubdiv', 'legalServices', 'Register Lease Sub-division', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('transmitJointLease', 'registrationServices', 'Register Transmission of a Lease held Jointly', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('surveyPlanCopy', 'informationServices', 'Survey Plan Copy', NULL, 'c', 1, 1.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regCessionLease', 'registrationServices', 'Register Cession of Lease', NULL, 'c', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);

--A Section with status 'x'
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('varyRight', 'registrationServices', 'Vary Right (General) Application::::kopo ea Fetola Tokelo', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Variation of <right> <reference>', NULL, 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('varyLease', 'registrationServices', 'Vary Lease Application::::kopo ea ho Fetola Lisi', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Variation of Lease <reference>', 'lease', 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('noteOccupation', 'registrationServices', 'Occupation Noted', NULL, 'x', 5, 5.00, 0.00, 0.01, 1, 'Occupation by <name> recorded', NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('newState', 'registrationServices', 'New State Title', NULL, 'x', 5, 0.00, 0.00, 0.00, 1, 'State Estate', NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regnStandardDocument', 'registrationServices', 'Registration of Standard Document::::Documento di Documento Standard', NULL, 'x', 3, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('newFreehold', 'registrationServices', 'New Freehold Title', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Fee Simple Estate', NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('newDigitalProperty', 'registrationServices', 'New Digital Property', NULL, 'x', 5, 0.00, 0.00, 0.00, 1, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('newApartment', 'registrationServices', 'New Apartment Title', NULL, 'x', 5, 5.00, 0.00, 0.02, 1, 'Apartment Estate', 'apartment', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cadastreExport', 'informationServices', 'Cadastre Export::::Export Catastale', NULL, 'x', 1, 0.00, 0.10, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('removeCaveat', 'registrationServices', 'Remove Caveat', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Caveat <reference> removed', 'caveat', 'cancel');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('varyCaveat', 'registrationServices', 'Vary Cavetionat Application', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, '<Caveat> <reference>', 'caveat', 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('historicOrder', 'registrationServices', 'Register Historic Preservation Order::::Registrazione ordine storico di precedenze', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Historic Preservation Order', 'noBuilding', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cadastreBulk', 'informationServices', 'Cadastre Bulk Export', NULL, 'x', 5, 5.00, 0.10, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('buildingRestriction', 'registrationServices', 'Register Building Restriction', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Building Restriction', 'noBuilding', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cadastrePrint', 'informationServices', 'Cadastre Print', NULL, 'x', 1, 0.50, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('usufruct', 'registrationServices', 'Register Usufruct', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, '<usufruct> right granted to <name>', 'usufruct', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('systematicRegn', 'registrationServices', 'Systematic Registration Claim', NULL, 'x', 90, 50.00, 0.00, 0.00, 1, 'Title issued at completion of systematic registration', 'ownership', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('surveyPlanCopy', 'informationServices', 'Survey Plan Copy', NULL, 'c', 1, 1.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('removeRight', 'registrationServices', 'Remove Right (General)::::Tlosa Tokelo', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, '<right> <reference> cancelled', NULL, 'cancel');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('waterRights', 'registrationServices', 'Register Water Rights', NULL, 'x', 5, 5.00, 0.01, 0.00, 1, 'Water Rights granted to <name>', 'waterrights', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('lifeEstate', 'registrationServices', 'Establish Life Estate', NULL, 'x', 5, 5.00, 0.00, 0.02, 1, 'Life Estate for <name1> with Remainder Estate in <name2, name3>', 'lifeEstate', 'new');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('limitedRoadAccess', 'registrationServices', 'Register Limited Road Access', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, 'Limited Road Access', 'limitedAccess', NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regnOnTitle', 'registrationServices', 'Registration on Title', NULL, 'x', 5, 5.00, 0.00, 0.01, 1, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('newDigitalTitle', 'registrationServices', 'Convert to Digital Title', NULL, 'x', 5, 0.00, 0.00, 0.00, 1, 'Title converted to digital format', NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('redefineCadastre', 'registrationServices', 'Redefine Cadastre', NULL, 'x', 30, 25.00, 0.10, 0.00, 1, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('removeRestriction', 'registrationServices', 'Remove Restriction::::Tlosa Thibelo', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, '<restriction> <reference> cancelled', NULL, 'cancel');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('TraceLeaseTransf', 'registrationServices', 'Trace Lease Transfers and Owners::::Tsoma phetisetso', NULL, 'x', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('applicationVaryLease', 'registrationServices', 'Sublease Variation Application::::kopo ea ho fetoloa ha Lisi', 'Transfer or Renew Lease', 'x', 20, 100.00, 0.00, 0.00, 1, 'Application of Variation of lease', 'lease', 'vary');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('cancelProperty', 'registrationServices', 'Cancel Title', NULL, 'x', 5, 5.00, 0.00, 0.00, 1, '', NULL, 'cancel');
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regnPowerOfAttorney', 'registrationServices', 'Register Power of Attorney', NULL, 'x', 3, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regDeedhypo', 'registrationServices', 'Register Deed of Hypothetication', NULL, 'x', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regAddendSublease', 'registrationServices', 'Register Addendum to the Sublease', NULL, 'x', 0, 5.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('regTitleDeed', 'registrationServices', 'Register Title Deed::::Ngolisa Title deed', NULL, 'x', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('endorsement', 'registrationServices', 'Apply and Register Endorsement', NULL, 'x', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('LeaseEndoInherit', 'registrationServices', 'Register Lease Endorsement ', NULL, 'x', 0, 0.00, 0.00, 0.00, 0, NULL, NULL, NULL);
INSERT INTO application.request_type(code,request_category_code,display_value,description,status,nr_days_to_complete,base_fee,area_base_fee,value_base_fee,nr_properties_required,notation_template,rrr_type_code,type_action_code) VALUES ('variationMortgage', 'registrationServices', 'Change Mortgage::::Phetoho ea Mortgage', 'Variation of Mortgage', 'x', 20, 100.00, 0.00, 0.00, 1, 'Variation of mortgage <reference>', 'mortgage', 'vary');

-- Completed on 2013-03-19 08:49:34

--
-- PostgreSQL database dump complete


